# Force dep to vendor the code generators, which aren't imported just used at dev time.
required = [
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "knative.dev/pkg/codegen/cmd/injection-gen",
  "knative.dev/caching/pkg/apis/caching/v1alpha1",
  "github.com/knative/test-infra/scripts",
  "github.com/knative/test-infra/tools/dep-collector",
]

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/api"
  revision = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  revision = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/client-go"
  revision = "kubernetes-1.13.1"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "=v0.1.10"

[[override]]
  name = "github.com/knative/test-infra"
  # HEAD as of 2019-06-18
  revision = "6c3132259e7b5062a719b393536c216397110e01"

[[constraint]]
  name = "github.com/jcrossley3/manifestival"
  branch = "master"

[[constraint]]
  name = "knative.dev/pkg"
  branch = "master"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[prune.project]]
  name = "k8s.io/code-generator"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "github.com/knative/test-infra"
  non-go = false

[[prune.project]]
  name = "knative.dev/pkg"
  non-go = false
  unused-packages = false
