# Force dep to vendor the code generators, which aren't imported just used at dev time.
required = [
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "knative.dev/pkg/codegen/cmd/injection-gen",
  "knative.dev/caching/pkg/apis/caching/v1alpha1",
  "knative.dev/test-infra/scripts",
  "knative.dev/test-infra/tools/dep-collector",
]

[[override]]
  name = "k8s.io/kube-openapi"
  revision = "0cf8f7e6ed1d2e3d47d02e3b6e559369af24d803"

[[override]]
  name = "github.com/go-openapi/spec"
  branch = "master"

[[override]]
  name = "sigs.k8s.io/controller-tools"
  revision = "9d55346c2bde73fb3326ac22eac2e5210a730207"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.15.3"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.15.3"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.15.3"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.15.3"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.15.3"

[[override]]
  name = "k8s.io/metrics"
  version = "kubernetes-1.15.3"

[[constraint]]
  name = "github.com/jcrossley3/manifestival"
  branch = "immutable-transform"

[[constraint]]
  name = "knative.dev/pkg"
  branch = "master"

[[override]]
  name = "knative.dev/test-infra"
  branch = "master"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[prune.project]]
  name = "k8s.io/code-generator"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "k8s.io/gengo"
  non-go = false

[[prune.project]]
  name = "knative.dev/test-infra"
  non-go = false

[[prune.project]]
  name = "knative.dev/pkg"
  non-go = false
  unused-packages = false

[[prune.project]]
  name = "k8s.io/code-generator"
  unused-packages = false
  non-go = false
